audioTextClassification/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path('', include('emotionDetection.urls', namespace='emotionDetection'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emotionDetection/urls.py
from django.urls import path
from .views import home, text_input, audio_input

app_name = 'emotionDetection'

urlpatterns = [
    path('', home, name='home'),
    path('text/', text_input, name='text_input'),
    path('audio/', audio_input, name='audio_input'),

]

emotionDetection/models.py
from django.db import models
from django.dispatch import receiver
import os


# Create your models here.
class UploadFile(models.Model):
    """
    Store file in folder
    """
    file = models.FileField(upload_to='audio/')


@receiver(models.signals.post_delete, sender=UploadFile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

emotionDetection/views.py
from django.shortcuts import render, HttpResponse, redirect
from .analysis import text_to_emotion, get_large_audio_transcription
from .models import UploadFile


# Create your views here.
def home(request):
    """
    Show the home page
    :param request: http headers
    :return: html object
    """
    data = {
        'title': 'Emotion Detection'
    }
    return render(request, 'index.html', context=data)


def text_input(request):
    """
    get the text from html and pass it to analysis.py file to detect the emotion
    :param request: http headers
    :return: html object
    """
    # print(request)
    if request.method == "POST":
        input_text = request.POST.get('text')
        # call emotion detection function and pass text
        results = text_to_emotion(input_text)

        data = {
            'title': 'Result of Emotion Detection',
            'results': results,
            'text': input_text,
            'top': results[0]
        }
        # print(data)
        return render(request, 'index.html', context=data)
        # return redirect('emotionDetection:home')
    return redirect('emotionDetection:home')


def audio_input(request):
    """
    get the audio file from html and pass it to analysis.py file to detect the emotion
    :param request: http headers
    :return: html object
    """
    # print(request)
    if request.method == "POST":
        # get file from html
        input_text = request.FILES.get('video-file-upload')
        # print(input_text)
        # save file as object in model
        file_obj = UploadFile()
        file_obj.file = input_text
        file_obj.save()
        # Get last objects from database
        new_f = UploadFile.objects.last()
        # url of file location
        add_url = str(new_f.file.url)
        # F=file location of audio
        print(f'E:/AudioTextA/{add_url[1:]}')
        path = f'E:/AudioTextA/{add_url[1:]}'
        # E:\AudioTextA\media\audio\english - conversation - practice - canceling - plans - ytmp4converter.com - en.mp3
        # pass file path to extract text from speech
        text = get_large_audio_transcription(path)
        # call emotion detection function and pass text
        results = text_to_emotion(text)
        data = {
            'title': 'Result of Emotion Detection',
            'results': results,
            'text': text,
            'top': results[0]
        }
        # print(data)
        # after processing delete the object and file
        new_f.delete()
        return render(request, 'index.html', context=data)
    return redirect('emotionDetection:home')

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
</head>

<body>
<style>
    .spinner-border {
        height: 20px;
        width: 20px;
    }
</style>
<div class="background-image">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <div class="upload-section hover-2">
                    <h2>Type or Paste Your Text </h2>
                    <form method="post" action="{% url 'emotionDetection:text_input' %}"> {% csrf_token %}
                        <div class="form-group">
                            <label for="text-file-upload">Maximum Number of Word 500:</label>
                            <textarea type=" text" name="text" placeholder="Enter text..." class="form-control-file"
                                      oninput="auto_grow(this)"></textarea>
                        </div>
                        <button type="submit" id="send-button" style="width: 100%" class="btn btn-primary">Submit
                        </button>
                    </form>
                </div>
            </div>

            <div class="col-md-6 col-lg-5">
                <div class="upload-section hover-2">
                    <h2>Upload Audio File</h2>
                    <form method="post" action="{% url 'emotionDetection:audio_input' %}" enctype='multipart/form-data'>{% csrf_token %}
                        <div class="form-group">
                            <label for="video-file-upload">Only .mp3 format and length <=2 minutes</label>
                            <input type="file" id="video-file-upload" name="video-file-upload"
                                   class="form-control-file" accept=".mp3">
                        </div>
                        <button type="submit" id="send-button-video" style="width: 100%" class="btn btn-primary">
                            Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% if title != 'Emotion Detection' %}
    <div id="scrolltome" class="container-fluid">
        <div class="row">
            <div class="col-md-6 pt-5">
                <h2>Result </h2>
                <div class="progress-group">
                    {% for result in results %}
                        <div class="progress-group-header">
                            <i class="cil-user progress-group-icon"></i>
                            <div><b>{{ result.label }}</b></div>
                            <div class="ml-auto font-weight-bold">{{ result.score }}%</div>
                        </div>
                        <div class="progress-group-bars">
                            <div class="progress progress-xs">
                                <div class="progress-bar  bg-dark " role="progressbar"
                                     style="width: {{ result.score }}%" aria-valuenow="{{ result.score }}"
                                     aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>


            <div class="col-md-6 pt-5">
                <h2>Text </h2>
                <div class="card bg-light mb-3 " style="max-width: 350rem;">
                    <div class="card-header">This text sounds like {{ top.label }}</div>
                    <div class="card-body">
                        {#                        <h5 class="card-title">Light card title</h5>#}
                        <p class="card-text">{{ text }}</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endif %}





<footer class="bg-light text-center text-lg-start pt-5">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        
        <a class="text-dark" href="#"><h5>Speech Emotion Detection and Text Analysis Using Google API  and Deep Learning
        </h5></a>
    </div>
    <!-- Copyright -->
</footer>


<script>
    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight) + "px";
    }

    var wordLen = 255; // Maximum word length
    function checkWordLen(obj) {
        var len = obj.value.split(/[\s]+/);
        if (len.length > wordLen) {
            alert("You cannot put more than " + wordLen + " words in this text area.");
            obj.oldValue = obj.value != obj.oldValue ? obj.value : obj.oldValue;
            obj.value = obj.oldValue ? obj.oldValue : "";
            return false;
        }
        return true;
    }
</script>


<script type="text/javascript" src="{% static 'assets/myscripts.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper-core.min.js"
        integrity="sha384-YDUJ9mJbz7QKsJfbhIXDPeFbUwMNl0eBb0LykrBWUPOGeMdTBl0LxOJKfwWq3giH"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{#Ajax Calls#}
<script>
    jQuery(function ($) {
        $(document).ajaxSend(function () {
            $("spinner-border").fadeIn(500000);

            var loading = '<div class="spinner-border"></div>&nbsp;&nbsp; Please wait...'
            $("#send-button").html(loading);
        });

        $("#send-button").click(function () {
            $.ajax({
                type: 'GET',
                success: function (data) {
                    console.log(data);
                }
            }).done(function () {
                setTimeout(function () {
                    $(".spinner-border").fadeOut(500000);
                }, 700);
            });
        });
    });
</script>
<script>
    jQuery(function ($) {
        $(document).ajaxSend(function () {
            $("spinner-border").fadeIn(500000);

            var loading = '<div class="spinner-border"></div>&nbsp;&nbsp; Please wait...'
            $("#send-button-video").html(loading);
        });

        $("#send-button-video").click(function () {
            $.ajax({
                type: 'GET',
                success: function (data) {
                    console.log(data);
                }
            }).done(function () {
                setTimeout(function () {
                    $(".spinner-border").fadeOut(500000);
                }, 700);
            });
        });
    });
</script>
{% if title != 'Emotion Detection' %}
    <script>
        window.scrollTo(0, $('#scrolltome').offset().top)
    </script>
{% endif %}
</body>

</html>